server:
  port: 8001
  
spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
