server:
  port: 8002
  
spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:postgresql://postgres:5432/kezbek_authorization
    username: authorization
    password: authorization123
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url: 
      defaultZone: http://discovery-server:8001/eureka

springdoc:
  paths-to-match: /oauth/token
